// packages/svelte/src/Menu.svelte
<script lang="ts">
import {
	FLUIX_SPRING,
	MENU_DEFAULTS,
	connectMenu,
	createMenuMachine,
	getMenuAttrs,
	type MenuMachineState,
	type MenuOrientation,
	type MenuVariant,
	type MenuTheme,
	type SpringConfig,
} from "@fluix-ui/core";
import { setContext } from "svelte";
import type { Snippet } from "svelte";

export interface MenuProps {
	orientation?: MenuOrientation;
	variant?: MenuVariant;
	theme?: MenuTheme;
	activeId?: string | null;
	defaultActiveId?: string | null;
	onActiveChange?: (id: string) => void;
	spring?: SpringConfig;
	roundness?: number;
	blur?: number;
	fill?: string;
	className?: string;
	children: Snippet;
}

const {
	orientation = MENU_DEFAULTS.orientation,
	variant = "pill",
	theme = "dark",
	activeId: controlledActiveId,
	defaultActiveId = null,
	onActiveChange,
	spring,
	roundness = MENU_DEFAULTS.roundness,
	blur: blurProp,
	fill,
	className,
	children,
}: MenuProps = $props();

const machine = createMenuMachine({
	orientation,
	variant,
	spring,
	roundness,
	blur: blurProp,
	fill,
	initialActiveId: controlledActiveId ?? defaultActiveId,
});

let snapshot = $state.raw<MenuMachineState>(machine.store.getSnapshot());

$effect(() => {
	return machine.store.subscribe(() => {
		snapshot = machine.store.getSnapshot();
	});
});

// Reconfigure machine when props change
$effect(() => {
	machine.configure({ orientation, variant, spring, roundness, blur: blurProp, fill });
});

// Sync controlled activeId
$effect(() => {
	if (controlledActiveId !== undefined) {
		machine.setActive(controlledActiveId ?? null);
	}
});

// Notify parent of active changes
let lastActiveNotified: string | null | undefined;
$effect(() => {
	const nextActiveId = snapshot.activeId;
	if (nextActiveId && lastActiveNotified !== nextActiveId && onActiveChange) {
		onActiveChange(nextActiveId);
	}
	lastActiveNotified = nextActiveId;
});

// Refs
let rootEl: HTMLElement | null = $state(null);
let indicatorEl: SVGRectElement | SVGPathElement | null = $state(null);
let size = $state({ width: 0, height: 0 });

const attrs = $derived(getMenuAttrs({ orientation, theme, variant }));
const springConfig = $derived(spring ?? FLUIX_SPRING);
const resolvedBlur = $derived(blurProp ?? Math.min(10, Math.max(6, roundness * 0.45)));
const isTab = $derived(variant === "tab");
const svgWidth = $derived(Math.max(1, size.width));
const svgHeight = $derived(Math.max(1, size.height));
const effectiveFill = $derived(fill ?? "var(--fluix-menu-indicator)");

const filterId = `fluix-menu-goo-${Math.random().toString(36).slice(2, 8)}`;

// Keep a mutable ref for activeId (non-reactive, for connectMenu callback)
let activeIdRef = snapshot.activeId;
$effect(() => {
	activeIdRef = snapshot.activeId;
});

// ResizeObserver for root
$effect(() => {
	const root = rootEl;
	if (!root) return;

	const measure = () => {
		const rect = root.getBoundingClientRect();
		const w = Math.ceil(rect.width);
		const h = Math.ceil(rect.height);
		if (size.width !== w || size.height !== h) {
			size = { width: w, height: h };
		}
	};

	measure();
	let raf = 0;
	const observer = new ResizeObserver(() => {
		cancelAnimationFrame(raf);
		raf = requestAnimationFrame(measure);
	});
	observer.observe(root);

	return () => {
		cancelAnimationFrame(raf);
		observer.disconnect();
	};
});

// Connect menu indicator
let connection: ReturnType<typeof connectMenu> | null = null;
$effect(() => {
	const root = rootEl;
	const indicator = indicatorEl;
	if (!root || !indicator) return;

	connection = connectMenu({
		root,
		indicator,
		getActiveId: () => activeIdRef,
		onSelect(id) {
			if (controlledActiveId === undefined) {
				machine.setActive(id);
			} else {
				onActiveChange?.(id);
			}
		},
		spring: springConfig,
		variant,
		orientation,
	});

	return () => {
		connection?.destroy();
		connection = null;
	};
});

// Sync indicator when activeId or size changes
$effect(() => {
	// Read dependencies
	snapshot.activeId;
	size.width;
	size.height;
	// Trigger sync
	connection?.sync(false);
});

// Cleanup machine
$effect(() => () => machine.destroy());

// Context for MenuItem
const setActive = (id: string) => {
	if (controlledActiveId === undefined) {
		machine.setActive(id);
	} else {
		onActiveChange?.(id);
	}
};

setContext("fluix-menu", {
	get activeId() { return snapshot.activeId; },
	setActive,
	get attrs() { return attrs; },
	get variant() { return variant; },
});
</script>

<nav
	bind:this={rootEl}
	{...attrs.root}
	class={className}
	aria-label="Fluix menu"
>
	<div {...attrs.canvas}>
		<svg
			xmlns="http://www.w3.org/2000/svg"
			width={svgWidth}
			height={svgHeight}
			viewBox="0 0 {svgWidth} {svgHeight}"
			aria-hidden="true"
		>
			{#if !isTab}
				<defs>
					<filter
						id={filterId}
						x="-20%" y="-20%" width="140%" height="140%"
						color-interpolation-filters="sRGB"
					>
						<feGaussianBlur in="SourceGraphic" stdDeviation={resolvedBlur} result="blur" />
						<feColorMatrix
							in="blur" type="matrix"
							values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 20 -10"
							result="goo"
						/>
						<feComposite in="SourceGraphic" in2="goo" operator="atop" />
					</filter>
				</defs>
			{/if}
			{#if isTab}
				<path
					bind:this={indicatorEl}
					{...attrs.indicator}
					d=""
					opacity={0}
					style:fill={effectiveFill}
				/>
			{:else}
				<g filter="url(#{filterId})">
					<rect
						bind:this={indicatorEl}
						{...attrs.indicator}
						x={0}
						y={0}
						width={0}
						height={0}
						rx={0}
						ry={0}
						opacity={0}
						style:fill={effectiveFill}
					/>
				</g>
			{/if}
		</svg>
	</div>
	<div {...attrs.list}>
		{@render children()}
	</div>
</nav>

// packages/angular/src/menu.component.ts
import {
	AfterViewInit,
	ChangeDetectionStrategy,
	ChangeDetectorRef,
	Component,
	ContentChildren,
	ElementRef,
	EventEmitter,
	Input,
	NgZone,
	OnChanges,
	OnDestroy,
	Output,
	QueryList,
	SimpleChanges,
	ViewChild,
	inject,
	signal,
} from "@angular/core";
import { CommonModule } from "@angular/common";
import {
	FLUIX_SPRING,
	MENU_DEFAULTS,
	connectMenu,
	createMenuMachine,
	getMenuAttrs,
	type MenuMachine,
	type MenuMachineState,
	type MenuOrientation,
	type MenuVariant,
	type MenuTheme,
	type SpringConfig,
} from "@fluix-ui/core";
import { FluixAttrsDirective } from "./attrs.directive";
import { FluixMenuItemComponent } from "./menu-item.component";

const GOO_MATRIX = "1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 20 -10";

@Component({
	selector: "fluix-menu",
	standalone: true,
	imports: [CommonModule, FluixAttrsDirective, FluixMenuItemComponent],
	template: `
		<nav
			#rootEl
			[fluixAttrs]="attrs().root"
			aria-label="Fluix menu"
		>
			<div [fluixAttrs]="attrs().canvas">
				<svg
					xmlns="http://www.w3.org/2000/svg"
					[attr.width]="svgWidth()"
					[attr.height]="svgHeight()"
					[attr.viewBox]="'0 0 ' + svgWidth() + ' ' + svgHeight()"
					aria-hidden="true"
				>
					@if (!isTab()) {
						<defs>
							<filter
								[attr.id]="filterId"
								x="-20%" y="-20%" width="140%" height="140%"
								color-interpolation-filters="sRGB"
							>
								<feGaussianBlur in="SourceGraphic" [attr.stdDeviation]="resolvedBlur()" result="blur" />
								<feColorMatrix
									in="blur" type="matrix"
									[attr.values]="gooMatrix"
									result="goo"
								/>
								<feComposite in="SourceGraphic" in2="goo" operator="atop" />
							</filter>
						</defs>
					}
					@if (isTab()) {
						<path
							#indicatorEl
							[attr.data-fluix-menu-indicator]="''"
							d=""
							opacity="0"
							[attr.fill]="effectiveFill()"
						/>
					} @else {
						<g [attr.filter]="'url(#' + filterId + ')'">
							<rect
								#indicatorEl
								[attr.data-fluix-menu-indicator]="''"
								x="0"
								y="0"
								width="0"
								height="0"
								rx="0"
								ry="0"
								opacity="0"
								[attr.fill]="effectiveFill()"
							/>
						</g>
					}
				</svg>
			</div>
			<div [fluixAttrs]="attrs().list">
				<ng-content />
			</div>
		</nav>
	`,
	changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FluixMenuComponent implements AfterViewInit, OnChanges, OnDestroy {
	@Input() orientation: MenuOrientation = MENU_DEFAULTS.orientation;
	@Input() variant: MenuVariant = "pill";
	@Input() theme: MenuTheme = "dark";
	@Input() activeId?: string | null;
	@Input() defaultActiveId?: string | null;
	@Input() spring?: SpringConfig;
	@Input() roundness: number = MENU_DEFAULTS.roundness;
	@Input() blur?: number;
	@Input() fill?: string;
	@Output() activeIdChange = new EventEmitter<string>();

	@ViewChild("rootEl") rootElRef!: ElementRef<HTMLElement>;
	@ViewChild("indicatorEl") indicatorElRef!: ElementRef<SVGRectElement | SVGPathElement>;
	@ContentChildren(FluixMenuItemComponent) menuItems!: QueryList<FluixMenuItemComponent>;

	private ngZone = inject(NgZone);
	private cdr = inject(ChangeDetectorRef);

	private machine!: MenuMachine;
	private unsubscribe?: () => void;
	private connection?: ReturnType<typeof connectMenu>;
	private resizeObs?: ResizeObserver;
	private measureRaf = 0;
	private lastActiveNotified: string | null = null;

	readonly gooMatrix = GOO_MATRIX;
	readonly filterId = `fluix-menu-goo-${Math.random().toString(36).slice(2, 8)}`;

	readonly attrs = signal(getMenuAttrs({ orientation: MENU_DEFAULTS.orientation, theme: "dark", variant: "pill" }));
	readonly size = signal({ width: 0, height: 0 });
	readonly snapshot = signal<MenuMachineState>({ activeId: null, config: {} });

	readonly isTab = () => this.variant === "tab";
	readonly resolvedBlur = () => this.blur ?? Math.min(10, Math.max(6, this.roundness * 0.45));
	readonly effectiveFill = () => this.fill ?? "var(--fluix-menu-indicator)";
	readonly svgWidth = () => Math.max(1, this.size().width);
	readonly svgHeight = () => Math.max(1, this.size().height);

	constructor() {
		this.machine = createMenuMachine({
			orientation: this.orientation,
			variant: this.variant,
			spring: this.spring,
			roundness: this.roundness,
			blur: this.blur,
			fill: this.fill,
			initialActiveId: this.activeId ?? this.defaultActiveId ?? null,
		});
	}

	ngAfterViewInit(): void {
		this.attrs.set(getMenuAttrs({ orientation: this.orientation, theme: this.theme, variant: this.variant }));

		// Subscribe to machine store
		this.unsubscribe = this.machine.store.subscribe(() => {
			this.ngZone.run(() => {
				const snap = this.machine.store.getSnapshot();
				this.snapshot.set(snap);

				// Fire activeIdChange callback
				if (snap.activeId && this.lastActiveNotified !== snap.activeId) {
					this.activeIdChange.emit(snap.activeId);
				}
				this.lastActiveNotified = snap.activeId;

				// Update item components
				this.updateItemStates(snap.activeId);

				this.connection?.sync(false);
				this.cdr.markForCheck();
			});
		});

		// Setup items
		this.setupItems();
		this.menuItems.changes.subscribe(() => this.setupItems());

		// ResizeObserver
		const root = this.rootElRef.nativeElement;
		const measure = () => {
			const rect = root.getBoundingClientRect();
			const w = Math.ceil(rect.width);
			const h = Math.ceil(rect.height);
			const prev = this.size();
			if (prev.width !== w || prev.height !== h) {
				this.size.set({ width: w, height: h });
				this.connection?.sync(false);
				this.cdr.markForCheck();
			}
		};

		this.resizeObs = new ResizeObserver(() => {
			cancelAnimationFrame(this.measureRaf);
			this.measureRaf = requestAnimationFrame(() => {
				this.ngZone.run(() => measure());
			});
		});
		this.resizeObs.observe(root);

		// Connect menu
		requestAnimationFrame(() => {
			measure();
			this.connectIndicator();
		});
	}

	ngOnChanges(changes: SimpleChanges): void {
		if (!this.machine) return;

		if (
			changes["orientation"] ||
			changes["variant"] ||
			changes["spring"] ||
			changes["roundness"] ||
			changes["blur"] ||
			changes["fill"]
		) {
			this.machine.configure({
				orientation: this.orientation,
				variant: this.variant,
				spring: this.spring,
				roundness: this.roundness,
				blur: this.blur,
				fill: this.fill,
			});
		}

		if (changes["activeId"] && this.activeId !== undefined) {
			this.machine.setActive(this.activeId ?? null);
		}

		if (changes["orientation"] || changes["theme"] || changes["variant"]) {
			this.attrs.set(getMenuAttrs({ orientation: this.orientation, theme: this.theme, variant: this.variant }));
		}

		// Reconnect if variant/orientation/spring changed
		if (changes["variant"] || changes["orientation"] || changes["spring"]) {
			this.reconnectIndicator();
		}
	}

	ngOnDestroy(): void {
		this.unsubscribe?.();
		this.connection?.destroy();
		cancelAnimationFrame(this.measureRaf);
		this.resizeObs?.disconnect();
		this.machine.destroy();
	}

	private setupItems(): void {
		if (!this.menuItems) return;
		const snap = this.machine.store.getSnapshot();
		const a = this.attrs();
		this.menuItems.forEach((item) => {
			const active = snap.activeId === item.menuId;
			item.active = active;
			item.itemAttrs = a.item({ id: item.menuId, active, disabled: item.disabled });
			item.select.subscribe((id: string) => {
				if (this.activeId === undefined) {
					this.machine.setActive(id);
				} else {
					this.activeIdChange.emit(id);
				}
			});
		});
	}

	private updateItemStates(activeId: string | null): void {
		if (!this.menuItems) return;
		const a = this.attrs();
		this.menuItems.forEach((item) => {
			const active = activeId === item.menuId;
			item.active = active;
			item.itemAttrs = a.item({ id: item.menuId, active, disabled: item.disabled });
		});
	}

	private connectIndicator(): void {
		const root = this.rootElRef?.nativeElement;
		const indicator = this.indicatorElRef?.nativeElement;
		if (!root || !indicator) return;

		this.connection = connectMenu({
			root,
			indicator,
			getActiveId: () => this.snapshot().activeId,
			onSelect: (id) => {
				if (this.activeId === undefined) {
					this.machine.setActive(id);
				} else {
					this.activeIdChange.emit(id);
				}
			},
			spring: this.spring ?? FLUIX_SPRING,
			variant: this.variant,
			orientation: this.orientation,
		});

		this.connection.sync(false);
	}

	private reconnectIndicator(): void {
		if (!this.rootElRef?.nativeElement) return;
		this.connection?.destroy();
		this.connectIndicator();
	}
}
