// packages/svelte/src/ToastItem.svelte
<script lang="ts">
import {
	Toaster as CoreToaster,
	type FluixToastItem,
	TOAST_DEFAULTS,
	type ToastMachine,
} from "@fluix/core";

const WIDTH = 350;
const HEIGHT = 40;
const PILL_CONTENT_PADDING = 16;
const HEADER_HORIZONTAL_PADDING_PX = 12;
const MIN_EXPAND_RATIO = 2.25;
const BODY_MERGE_OVERLAP = 6;
const DISMISS_STAGE_DELAY_MS = 260;

interface Props {
	item: FluixToastItem;
	machine: ToastMachine;
	localState: { ready: boolean; expanded: boolean };
	onLocalStateChange: (patch: Partial<{ ready: boolean; expanded: boolean }>) => void;
}

const { item, machine, localState, onLocalStateChange }: Props = $props();

// --- Element refs ---
const rootEl: HTMLButtonElement | undefined = $state();
const headerEl: HTMLElement | undefined = $state();
const headerInnerEl: HTMLElement | undefined = $state();
const contentEl: HTMLElement | undefined = $state();

// --- Reactive measurements ---
let pillWidth = $state(HEIGHT);
let contentHeight = $state(0);
let frozenExpanded = $state(HEIGHT * MIN_EXPAND_RATIO);

// --- Transient flags (plain vars, NOT $state — must not trigger $effect re-runs) ---
let hoveringFlag = false;
let pendingDismissFlag = false;
let dismissRequestedFlag = false;
let dismissTimerHandle: ReturnType<typeof setTimeout> | null = null;

// --- Derived values ---
function getPillAlign(position: string): "left" | "center" | "right" {
	if (position.includes("right")) return "right";
	if (position.includes("center")) return "center";
	return "left";
}

const attrs = $derived(CoreToaster.getAttrs(item, localState));
const hasDescription = $derived(Boolean(item.description) || Boolean(item.button));
const isLoading = $derived(item.state === "loading");
const open = $derived(hasDescription && localState.expanded && !isLoading);
const edge = $derived(item.position.startsWith("top") ? "bottom" : "top");
const pillAlign = $derived(getPillAlign(item.position));
const filterId = $derived(`fluix-gooey-${item.id.replace(/[^a-z0-9-]/gi, "-")}`);
const roundness = $derived(item.roundness ?? TOAST_DEFAULTS.roundness);
const blur = $derived(Math.min(10, Math.max(6, roundness * 0.45)));
const minExpanded = HEIGHT * MIN_EXPAND_RATIO;

const rawExpanded = $derived(
	hasDescription ? Math.max(minExpanded, HEIGHT + contentHeight) : minExpanded,
);

// Freeze expanded height when open
$effect(() => {
	if (open) frozenExpanded = rawExpanded;
});
// Update frozen while open
$effect(() => {
	if (open) frozenExpanded = rawExpanded;
});

const expanded = $derived(open ? rawExpanded : frozenExpanded);
const expandedContent = $derived(Math.max(0, expanded - HEIGHT));
const expandedHeight = $derived(hasDescription ? Math.max(expanded, minExpanded) : HEIGHT);
const resolvedPillWidth = $derived(Math.max(HEIGHT, pillWidth));
const pillX = $derived(
	pillAlign === "right"
		? WIDTH - resolvedPillWidth
		: pillAlign === "center"
			? (WIDTH - resolvedPillWidth) / 2
			: 0,
);

const rootStyleObj = $derived({
	"--_h": `${open ? expanded : HEIGHT}px`,
	"--_pw": `${resolvedPillWidth}px`,
	"--_px": `${pillX}px`,
	"--_ht": `translateY(${open ? (edge === "bottom" ? 3 : -3) : 0}px) scale(${open ? 0.9 : 1})`,
	"--_co": `${open ? 1 : 0}`,
	"--_cy": `${open ? 0 : -14}px`,
	"--_cm": `${open ? expandedContent : 0}px`,
	"--_by": `${open ? HEIGHT - BODY_MERGE_OVERLAP : HEIGHT}px`,
	"--_bh": `${open ? expandedContent : 0}px`,
	"--_bo": `${open ? 1 : 0}`,
});

// --- Helper functions ---
function clearDismissTimer() {
	if (dismissTimerHandle) {
		clearTimeout(dismissTimerHandle);
		dismissTimerHandle = null;
	}
}

function requestDismiss() {
	if (dismissRequestedFlag) return;
	dismissRequestedFlag = true;
	hoveringFlag = false;
	pendingDismissFlag = false;
	onLocalStateChange({ expanded: false });
	clearDismissTimer();
	const delay = hasDescription ? DISMISS_STAGE_DELAY_MS : 0;
	dismissTimerHandle = setTimeout(() => {
		machine.dismiss(item.id);
		dismissTimerHandle = null;
	}, delay);
}

// --- Effects ---

// Apply CSS custom properties to root element
$effect(() => {
	const el = rootEl;
	if (!el) return;
	const style = rootStyleObj;
	for (const [key, value] of Object.entries(style)) {
		el.style.setProperty(key, value);
	}
});

// Measure pill width (synchronous initial measure, rAF-debounced for resize)
$effect(() => {
	const headerElement = headerEl;
	const headerInner = headerInnerEl;
	if (!headerElement || !headerInner) return;

	const measure = () => {
		const cs = getComputedStyle(headerElement);
		const horizontalPadding =
			Number.parseFloat(cs.paddingLeft || "0") + Number.parseFloat(cs.paddingRight || "0");
		const intrinsicWidth = headerInner.getBoundingClientRect().width;
		pillWidth = intrinsicWidth + horizontalPadding + PILL_CONTENT_PADDING;
	};

	// Measure synchronously so pill is correct before ready transitions enable
	measure();

	let rafId = 0;
	const observer = new ResizeObserver(() => {
		cancelAnimationFrame(rafId);
		rafId = requestAnimationFrame(measure);
	});
	observer.observe(headerInner);

	return () => {
		cancelAnimationFrame(rafId);
		observer.disconnect();
	};
});

// Measure content height (runs after DOM update — Svelte $effect default)
$effect(() => {
	if (!hasDescription) {
		contentHeight = 0;
		return;
	}
	const el = contentEl;
	if (!el) return;

	const measure = () => {
		contentHeight = el.scrollHeight;
	};
	measure();

	let rafId = 0;
	const observer = new ResizeObserver(() => {
		cancelAnimationFrame(rafId);
		rafId = requestAnimationFrame(measure);
	});
	observer.observe(el);

	return () => {
		cancelAnimationFrame(rafId);
		observer.disconnect();
	};
});

// Ready timer (32ms after mount)
$effect(() => {
	const timer = setTimeout(() => {
		onLocalStateChange({ ready: true });
	}, 32);
	return () => clearTimeout(timer);
});

// Auto-dismiss timer
$effect(() => {
	// Track deps for re-run
	const id = item.id;
	const instanceId = item.instanceId;
	const duration = item.duration;
	void id;
	void instanceId;

	if (duration == null || duration <= 0) return;

	const timer = setTimeout(() => {
		if (hoveringFlag) {
			pendingDismissFlag = true;
			return;
		}
		pendingDismissFlag = false;
		requestDismiss();
	}, duration);

	return () => clearTimeout(timer);
});

// Autopilot timers
$effect(() => {
	if (!localState.ready) return;
	// Track deps
	void item.id;
	void item.instanceId;

	const timers: ReturnType<typeof setTimeout>[] = [];

	if (item.autoExpandDelayMs != null && item.autoExpandDelayMs > 0) {
		timers.push(
			setTimeout(() => {
				if (dismissRequestedFlag) return;
				if (!hoveringFlag) onLocalStateChange({ expanded: true });
			}, item.autoExpandDelayMs),
		);
	}

	if (item.autoCollapseDelayMs != null && item.autoCollapseDelayMs > 0) {
		timers.push(
			setTimeout(() => {
				if (dismissRequestedFlag) return;
				if (!hoveringFlag) onLocalStateChange({ expanded: false });
			}, item.autoCollapseDelayMs),
		);
	}

	return () => {
		for (const t of timers) clearTimeout(t);
	};
});

// Reset flags on instanceId change
$effect(() => {
	void item.instanceId;
	hoveringFlag = false;
	pendingDismissFlag = false;
	dismissRequestedFlag = false;
	clearDismissTimer();
});

// Connect DOM events
$effect(() => {
	const el = rootEl;
	if (!el) return;

	// Capture current item for the closure
	const currentItem = item;

	const callbacks = {
		onExpand: () => {
			if (currentItem.exiting || dismissRequestedFlag) return;
			onLocalStateChange({ expanded: true });
		},
		onCollapse: () => {
			if (currentItem.exiting || dismissRequestedFlag) return;
			if (currentItem.autopilot !== false) return;
			onLocalStateChange({ expanded: false });
		},
		onDismiss: () => requestDismiss(),
		onHoverStart: () => {
			hoveringFlag = true;
		},
		onHoverEnd: () => {
			hoveringFlag = false;
			if (pendingDismissFlag && !dismissRequestedFlag) {
				pendingDismissFlag = false;
				requestDismiss();
			}
		},
	};

	const { destroy } = CoreToaster.connect(el, callbacks, currentItem);
	return destroy;
});
</script>

{#snippet iconFor(state: FluixToastState)}
	{#if state === "success"}
		<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
			<polyline points="20 6 9 17 4 12" />
		</svg>
	{:else if state === "error"}
		<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
			<line x1="18" y1="6" x2="6" y2="18" />
			<line x1="6" y1="6" x2="18" y2="18" />
		</svg>
	{:else if state === "warning"}
		<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
			<path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z" />
			<line x1="12" y1="9" x2="12" y2="13" />
			<line x1="12" y1="17" x2="12.01" y2="17" />
		</svg>
	{:else if state === "info"}
		<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
			<circle cx="12" cy="12" r="10" />
			<line x1="12" y1="16" x2="12" y2="12" />
			<line x1="12" y1="8" x2="12.01" y2="8" />
		</svg>
	{:else if state === "loading"}
		<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" data-fluix-icon="spin">
			<line x1="12" y1="2" x2="12" y2="6" />
			<line x1="12" y1="18" x2="12" y2="22" />
			<line x1="4.93" y1="4.93" x2="7.76" y2="7.76" />
			<line x1="16.24" y1="16.24" x2="19.07" y2="19.07" />
			<line x1="2" y1="12" x2="6" y2="12" />
			<line x1="18" y1="12" x2="22" y2="12" />
			<line x1="4.93" y1="19.07" x2="7.76" y2="16.24" />
			<line x1="16.24" y1="7.76" x2="19.07" y2="4.93" />
		</svg>
	{:else if state === "action"}
		<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
			<circle cx="12" cy="12" r="10" />
			<polygon points="10 8 16 12 10 16 10 8" fill="currentColor" stroke="none" />
		</svg>
	{/if}
{/snippet}

<button
	bind:this={rootEl}
	type="button"
	{...attrs.root}
>
	<div {...attrs.canvas}>
		<svg
			xmlns="http://www.w3.org/2000/svg"
			data-fluix-svg=""
			width={WIDTH}
			height={expandedHeight}
			viewBox="0 0 {WIDTH} {expandedHeight}"
			aria-hidden="true"
			style="position:absolute;left:0;top:0;overflow:visible;"
		>
			<defs>
				<filter
					id={filterId}
					x="-20%" y="-20%" width="140%" height="140%"
					color-interpolation-filters="sRGB"
				>
					<feGaussianBlur in="SourceGraphic" stdDeviation={blur} result="blur" />
					<feColorMatrix
						in="blur" type="matrix"
						values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 20 -10"
						result="goo"
					/>
					<feComposite in="SourceGraphic" in2="goo" operator="atop" />
				</filter>
			</defs>
			<g filter="url(#{filterId})">
				<rect
					data-fluix-pill=""
					x={pillX} y={0}
					width={resolvedPillWidth} height={HEIGHT}
					rx={roundness} ry={roundness}
					fill={item.fill ?? "#FFFFFF"}
				/>
				<rect
					data-fluix-body=""
					x={0} y={HEIGHT}
					width={WIDTH} height={0}
					rx={0} ry={0}
					fill={item.fill ?? "#FFFFFF"}
					opacity={0}
				/>
			</g>
		</svg>
	</div>

	<div
		bind:this={headerEl}
		{...attrs.header}
		style="padding-left:{HEADER_HORIZONTAL_PADDING_PX}px;padding-right:{HEADER_HORIZONTAL_PADDING_PX}px"
	>
		<div data-fluix-header-stack="">
			<div
				bind:this={headerInnerEl}
				data-fluix-header-inner=""
				data-layer="current"
			>
				<div {...attrs.badge} class={item.styles?.badge}>
					{#if item.icon != null}
						{#if typeof item.icon === "string"}
							<span aria-hidden="true">{item.icon}</span>
						{/if}
					{:else}
						{@render iconFor(item.state)}
					{/if}
				</div>
				<span {...attrs.title} class={item.styles?.title}>
					{item.title ?? item.state}
				</span>
			</div>
		</div>
	</div>

	{#if hasDescription}
		<div {...attrs.content}>
			<div
				bind:this={contentEl}
				{...attrs.description}
				class={item.styles?.description}
			>
				{#if typeof item.description === "string" || typeof item.description === "number"}
					{String(item.description)}
				{:else if typeof item.description === "function"}
					{@render (item.description as Snippet)()}
				{/if}

				{#if item.button}
					<button
						{...attrs.button}
						type="button"
						class={item.styles?.button}
						onclick={(e: MouseEvent) => { e.stopPropagation(); item.button?.onClick(); }}
					>
						{item.button.title}
					</button>
				{/if}
			</div>
		</div>
	{/if}
</button>

// packages/angular/src/toast-item.component.ts
/**
 * Single toast item: applies attrs from core, SVG gooey, connectToast, WAAPI pill animation.
 */

import {
	AfterViewInit,
	ChangeDetectionStrategy,
	Component,
	ElementRef,
	EventEmitter,
	Input,
	OnChanges,
	OnDestroy,
	Output,
	signal,
	SimpleChanges,
	ViewChild,
} from "@angular/core";
import { CommonModule } from "@angular/common";
import {
	Toaster as CoreToaster,
	FLUIX_SPRING,
	type FluixToastItem,
	type ToastAttrs,
	TOAST_DEFAULTS,
	animateSpring,
} from "@fluix-ui/core";
import { getToastRootVars } from "./toast-root-vars";
import { FluixAttrsDirective } from "./attrs.directive";
import { FluixToastIconComponent } from "./toast-icon.component";

const WIDTH = 350;
const HEIGHT = 40;
const PILL_PADDING = 10;
const MIN_EXPAND_RATIO = 2.25;
const BODY_MERGE_OVERLAP = 6;

function getPillAlign(position: FluixToastItem["position"]): "left" | "center" | "right" {
	if (position.includes("right")) return "right";
	if (position.includes("center")) return "center";
	return "left";
}

@Component({
	selector: "fluix-toast-item",
	standalone: true,
	imports: [CommonModule, FluixAttrsDirective, FluixToastIconComponent],
	template: `
		<button
			type="button"
			#rootEl
			[fluixAttrs]="attrs.root"
			[ngStyle]="rootVars"
		>
			<div [fluixAttrs]="attrs.canvas">
				<svg
					[attr.xmlns]="'http://www.w3.org/2000/svg'"
					data-fluix-svg
					[attr.width]="WIDTH"
					[attr.height]="svgHeight"
					[attr.viewBox]="viewBox"
					aria-hidden
				>
					<defs>
						<filter
							[id]="filterId"
							x="-20%"
							y="-20%"
							width="140%"
							height="140%"
							colorInterpolationFilters="sRGB"
						>
							<feGaussianBlur in="SourceGraphic" [attr.stdDeviation]="blur" result="blur" />
							<feColorMatrix
								in="blur"
								type="matrix"
								values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 20 -10"
								result="goo"
							/>
							<feComposite in="SourceGraphic" in2="goo" operator="atop" />
						</filter>
					</defs>
					<g [attr.filter]="'url(#' + filterId + ')'">
						<rect
							#pillRef
							data-fluix-pill
							[attr.x]="pillX"
							y="0"
							[attr.width]="resolvedPillWidth"
							[attr.height]="HEIGHT"
							[attr.rx]="roundness"
							[attr.ry]="roundness"
							[attr.fill]="item.fill ?? '#FFFFFF'"
						/>
						<rect
							data-fluix-body
							x="0"
							[attr.y]="HEIGHT"
							[attr.width]="WIDTH"
							height="0"
							[attr.rx]="roundness"
							[attr.ry]="roundness"
							[attr.fill]="item.fill ?? '#FFFFFF'"
							opacity="0"
						/>
					</g>
				</svg>
			</div>

			<div #headerRef data-fluix-header [fluixAttrs]="attrs.header">
				<div data-fluix-header-stack>
					<div data-fluix-header-inner data-layer="current">
						<div [fluixAttrs]="attrs.badge" [attr.data-state]="item.state" [class]="item.styles?.badge ?? ''">
							<fluix-toast-icon [state]="item.state" [icon]="item.icon" />
						</div>
						<span [fluixAttrs]="attrs.title" [attr.data-state]="item.state" [class]="item.styles?.title ?? ''">
							{{ item.title ?? item.state }}
						</span>
					</div>
				</div>
			</div>

			@if (hasDesc) {
				<div [fluixAttrs]="attrs.content">
					<div #contentRef [fluixAttrs]="attrs.description" [class]="item.styles?.description ?? ''">
						{{ item.description }}
						@if (item.button) {
							<button
								type="button"
								[fluixAttrs]="attrs.button"
								[class]="item.styles?.button ?? ''"
								(click)="onButtonClick($event)"
							>
								{{ item.button.title }}
							</button>
						}
					</div>
				</div>
			}
		</button>
	`,
	changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FluixToastItemComponent implements AfterViewInit, OnChanges, OnDestroy {
	@ViewChild("rootEl") rootEl!: ElementRef<HTMLButtonElement>;
	@ViewChild("pillRef") pillRef!: ElementRef<SVGRectElement>;
	@ViewChild("contentRef") contentRef!: ElementRef<HTMLDivElement> | null;
	@ViewChild("headerRef") headerRef!: ElementRef<HTMLDivElement>;

	@Input({ required: true }) item!: FluixToastItem;
	@Input({ required: true }) localState!: { ready: boolean; expanded: boolean };
	@Output() localStateChange = new EventEmitter<Partial<{ ready: boolean; expanded: boolean }>>();

	readonly WIDTH = WIDTH;
	readonly HEIGHT = HEIGHT;

	readonly pillWidth = signal(0);
	readonly contentHeight = signal(0);

	private connectDestroy: (() => void) | null = null;
	private pillRo: ResizeObserver | null = null;
	private contentRo: ResizeObserver | null = null;
	private pillAnim: Animation | null = null;
	private pillFirst = true;
	private prevPill = { x: 0, width: HEIGHT, height: HEIGHT };
	private hovering = false;
	private pendingDismiss = false;
	private dismissRequested = false;
	private timers: ReturnType<typeof setTimeout>[] = [];
	private machine = CoreToaster.getMachine();

	ngOnChanges(changes: SimpleChanges): void {
		if (changes["localState"] && this.rootEl?.nativeElement) {
			queueMicrotask(() => this.runPillAnimation());
		}
	}

	get attrs(): ToastAttrs {
		return CoreToaster.getAttrs(this.item, this.localState);
	}

	get roundness(): number {
		return this.item.roundness ?? TOAST_DEFAULTS.roundness;
	}

	get hasDesc(): boolean {
		return Boolean(this.item.description) || Boolean(this.item.button);
	}

	get edge(): "top" | "bottom" {
		return this.item.position.startsWith("top") ? "bottom" : "top";
	}

	get open(): boolean {
		return this.hasDesc && this.localState.expanded && this.item.state !== "loading";
	}

	get minExpanded(): number {
		return HEIGHT * MIN_EXPAND_RATIO;
	}

	get rawExpanded(): number {
		return this.hasDesc
			? Math.max(this.minExpanded, HEIGHT + this.contentHeight())
			: this.minExpanded;
	}

	frozenExpanded = this.minExpanded;

	get expanded(): number {
		if (this.open) {
			this.frozenExpanded = this.rawExpanded;
		}
		return this.open ? this.rawExpanded : this.frozenExpanded;
	}

	get expandedContent(): number {
		return Math.max(0, this.expanded - HEIGHT);
	}

	get svgHeight(): number {
		return this.hasDesc ? Math.max(this.expanded, this.minExpanded) : HEIGHT;
	}

	get viewBox(): string {
		return `0 0 ${WIDTH} ${this.svgHeight}`;
	}

	get blur(): number {
		return Math.min(10, Math.max(6, this.roundness * 0.45));
	}

	get filterId(): string {
		return `fluix-gooey-${this.item.id.replace(/[^a-z0-9-]/gi, "-")}`;
	}

	get position(): "left" | "center" | "right" {
		return getPillAlign(this.item.position);
	}

	get resolvedPillWidth(): number {
		return Math.max(this.pillWidth() || HEIGHT, HEIGHT);
	}

	get pillHeight(): number {
		return HEIGHT + this.blur * 3;
	}

	get pillX(): number {
		const w = this.resolvedPillWidth;
		if (this.position === "right") return WIDTH - w;
		if (this.position === "center") return (WIDTH - w) / 2;
		return 0;
	}

	get rootVars(): Record<string, string> {
		return getToastRootVars({
			open: this.open,
			expanded: this.expanded,
			height: HEIGHT,
			resolvedPillWidth: this.resolvedPillWidth,
			pillX: this.pillX,
			edge: this.edge,
			expandedContent: this.expandedContent,
			bodyMergeOverlap: BODY_MERGE_OVERLAP,
		});
	}

	ngAfterViewInit(): void {
		const el = this.rootEl?.nativeElement;
		if (!el) return;

		const callbacks = {
			onExpand: () => {
				if (this.item.exiting || this.dismissRequested) return;
				this.localStateChange.emit({ expanded: true });
			},
			onCollapse: () => {
				if (this.item.exiting || this.dismissRequested) return;
				if (this.item.autopilot !== false) return;
				this.localStateChange.emit({ expanded: false });
			},
			onDismiss: () => {
				if (this.dismissRequested) return;
				this.dismissRequested = true;
				this.machine.dismiss(this.item.id);
			},
			onHoverStart: () => {
				this.hovering = true;
			},
			onHoverEnd: () => {
				this.hovering = false;
				if (this.pendingDismiss) {
					this.pendingDismiss = false;
					if (!this.dismissRequested) {
						this.dismissRequested = true;
						this.machine.dismiss(this.item.id);
					}
				}
			},
		};

		const conn = CoreToaster.connect(el, callbacks, this.item);
		this.connectDestroy = conn.destroy;

		// Mark ready after mount
		this.timers.push(
			setTimeout(() => {
				this.localStateChange.emit({ ready: true });
			}, 32),
		);

		// Measure pill (header inner width)
		const headerEl = this.headerRef?.nativeElement;
		const inner = headerEl?.querySelector("[data-fluix-header-inner]");
		if (inner) {
			const measurePill = () => {
				const pad = 12 + 12;
				const w = (inner as HTMLElement).scrollWidth + pad + PILL_PADDING;
				if (w > PILL_PADDING) {
					this.pillWidth.set(w);
					queueMicrotask(() => this.runPillAnimation());
				}
			};
			measurePill();
			this.pillRo = new ResizeObserver(() => measurePill());
			this.pillRo.observe(inner);
		}

		if (this.hasDesc && this.contentRef?.nativeElement) {
			const contentEl = this.contentRef.nativeElement;
			const measureContent = () => {
				this.contentHeight.set(contentEl.scrollHeight);
				queueMicrotask(() => this.runPillAnimation());
			};
			measureContent();
			this.contentRo = new ResizeObserver(() => measureContent());
			this.contentRo.observe(contentEl);
		}

		// Auto-dismiss
		const duration = this.item.duration;
		if (duration != null && duration > 0) {
			this.timers.push(
				setTimeout(() => {
					if (this.hovering) {
						this.pendingDismiss = true;
						this.timers.push(
							setTimeout(() => {
								if (!this.dismissRequested) {
									this.dismissRequested = true;
									this.pendingDismiss = false;
									this.machine.dismiss(this.item.id);
								}
							}, 1200),
						);
						return;
					}
					this.dismissRequested = true;
					this.machine.dismiss(this.item.id);
				}, duration),
			);
		}

		// Autopilot expand/collapse
		if (this.item.autoExpandDelayMs != null && this.item.autoExpandDelayMs > 0) {
			this.timers.push(
				setTimeout(() => {
					if (!this.hovering) this.localStateChange.emit({ expanded: true });
				}, this.item.autoExpandDelayMs),
			);
		}
		if (this.item.autoCollapseDelayMs != null && this.item.autoCollapseDelayMs > 0) {
			this.timers.push(
				setTimeout(() => {
					if (!this.hovering) this.localStateChange.emit({ expanded: false });
				}, this.item.autoCollapseDelayMs),
			);
		}

		// Pill WAAPI animation runs in a microtask after view so pillRef is set
		queueMicrotask(() => this.runPillAnimation());
	}

	ngOnDestroy(): void {
		this.connectDestroy?.();
		this.pillRo?.disconnect();
		this.contentRo?.disconnect();
		this.pillAnim?.cancel();
		this.timers.forEach(clearTimeout);
		this.timers = [];
	}

	private runPillAnimation(): void {
		const el = this.pillRef?.nativeElement;
		if (!el || !this.localState.ready) return;

		const next = {
			x: this.pillX,
			width: this.resolvedPillWidth,
			height: this.open ? this.pillHeight : HEIGHT,
		};

		if (
			this.prevPill.x === next.x &&
			this.prevPill.width === next.width &&
			this.prevPill.height === next.height
		) {
			return;
		}

		this.pillAnim?.cancel();

		if (this.pillFirst) {
			this.pillFirst = false;
			el.setAttribute("x", String(next.x));
			el.setAttribute("width", String(next.width));
			el.setAttribute("height", String(next.height));
			this.prevPill = next;
			return;
		}

		const anim = animateSpring(
			el,
			{
				x: { from: this.prevPill.x, to: next.x, unit: "px" },
				width: { from: this.prevPill.width, to: next.width, unit: "px" },
				height: { from: this.prevPill.height, to: next.height, unit: "px" },
			},
			FLUIX_SPRING,
		);
		this.pillAnim = anim;
		this.prevPill = next;
	}

	onButtonClick(e: Event): void {
		e.stopPropagation();
		this.item.button?.onClick();
	}
}
