// packages/react/src/menu.tsx
import {
	FLUIX_SPRING,
	MENU_DEFAULTS,
	connectMenu,
	createMenuMachine,
	getMenuAttrs,
	type MenuMachine,
	type MenuMachineState,
	type MenuOrientation,
	type MenuVariant,
	type MenuTheme,
	type SpringConfig,
} from "@fluix-ui/core";
import {
	type MouseEventHandler,
	type ReactNode,
	createContext,
	useCallback,
	useContext,
	useEffect,
	useId,
	useLayoutEffect,
	useMemo,
	useRef,
	useState,
	useSyncExternalStore,
} from "react";

const GOO_MATRIX = "1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 20 -10";

const EMPTY_STATE: MenuMachineState = {
	activeId: null,
	config: {},
};

function getServerSnapshot(): MenuMachineState {
	return EMPTY_STATE;
}

export interface MenuRootProps {
	orientation?: MenuOrientation;
	variant?: MenuVariant;
	theme?: MenuTheme;
	activeId?: string | null;
	defaultActiveId?: string | null;
	onActiveChange?(id: string): void;
	spring?: SpringConfig;
	roundness?: number;
	blur?: number;
	fill?: string;
	className?: string;
	children: ReactNode;
}

export interface MenuItemProps {
	id: string;
	disabled?: boolean;
	className?: string;
	children: ReactNode;
	onClick?: MouseEventHandler<HTMLButtonElement>;
}

export interface MenuIndicatorProps {
	fill?: string;
	blur?: number;
	className?: string;
}

interface MenuContextValue {
	activeId: string | null;
	setActive(id: string): void;
	registerIndicator(node: SVGRectElement | SVGPathElement | null): void;
	rootRef: React.RefObject<HTMLElement | null>;
	attrs: ReturnType<typeof getMenuAttrs>;
	filterId: string;
	fill?: string;
	blur: number;
	size: { width: number; height: number };
	variant: MenuVariant;
}

const MenuContext = createContext<MenuContextValue | null>(null);

function useMenuContext(): MenuContextValue {
	const context = useContext(MenuContext);
	if (!context) {
		throw new Error("Menu components must be used inside <Menu.Root>.");
	}
	return context;
}

function Root({
	orientation = MENU_DEFAULTS.orientation,
	variant = "pill",
	theme = "dark",
	activeId: controlledActiveId,
	defaultActiveId = null,
	onActiveChange,
	spring,
	roundness = MENU_DEFAULTS.roundness,
	blur,
	fill,
	className,
	children,
}: MenuRootProps) {
	const machineRef = useRef<MenuMachine | null>(null);
	if (machineRef.current === null) {
		machineRef.current = createMenuMachine({
			orientation,
			variant,
			spring,
			roundness,
			blur,
			fill,
			initialActiveId: controlledActiveId ?? defaultActiveId,
		});
	}
	const machine = machineRef.current;

	const subscribe = useCallback((cb: () => void) => machine.store.subscribe(cb), [machine]);
	const getSnapshot = useCallback(() => machine.store.getSnapshot(), [machine]);
	const snapshot = useSyncExternalStore(subscribe, getSnapshot, getServerSnapshot);

	const rootRef = useRef<HTMLElement | null>(null);
	const [indicatorNode, setIndicatorNode] = useState<SVGRectElement | SVGPathElement | null>(null);
	const [size, setSize] = useState({ width: 0, height: 0 });
	const activeIdRef = useRef<string | null>(snapshot.activeId);
	activeIdRef.current = snapshot.activeId;

	const connectionRef = useRef<ReturnType<typeof connectMenu> | null>(null);
	const lastActiveNotifiedRef = useRef<string | null>(snapshot.activeId);
	const controlledActiveIdRef = useRef(controlledActiveId);
	controlledActiveIdRef.current = controlledActiveId;
	const onActiveChangeRef = useRef(onActiveChange);
	onActiveChangeRef.current = onActiveChange;

	const reactFilterId = useId().replace(/:/g, "-");
	const filterId = `fluix-menu-goo-${reactFilterId}`;
	const attrs = useMemo(() => getMenuAttrs({ orientation, theme, variant }), [orientation, theme, variant]);
	const resolvedBlur = blur ?? Math.min(10, Math.max(6, roundness * 0.45));
	const springConfig = spring ?? FLUIX_SPRING;

	useEffect(() => {
		machine.configure({ orientation, variant, spring, roundness, blur, fill });
	}, [machine, orientation, variant, spring, roundness, blur, fill]);

	useEffect(() => {
		if (controlledActiveId !== undefined) {
			machine.setActive(controlledActiveId ?? null);
		}
	}, [controlledActiveId, machine]);

	useEffect(() => {
		const nextActiveId = snapshot.activeId;
		if (
			nextActiveId &&
			lastActiveNotifiedRef.current !== nextActiveId &&
			onActiveChange
		) {
			onActiveChange(nextActiveId);
		}
		lastActiveNotifiedRef.current = nextActiveId;
	}, [snapshot.activeId, onActiveChange]);

	useLayoutEffect(() => {
		const root = rootRef.current;
		if (!root) return;

		const measure = () => {
			const rect = root.getBoundingClientRect();
			const width = Math.ceil(rect.width);
			const height = Math.ceil(rect.height);
			setSize((prev) => {
				if (prev.width === width && prev.height === height) return prev;
				return { width, height };
			});
		};

		measure();
		let raf = 0;
		const observer = new ResizeObserver(() => {
			cancelAnimationFrame(raf);
			raf = requestAnimationFrame(measure);
		});
		observer.observe(root);

		return () => {
			cancelAnimationFrame(raf);
			observer.disconnect();
		};
	}, []);

	useEffect(() => {
		const root = rootRef.current;
		if (!root || !indicatorNode) return;

		const connection = connectMenu({
			root,
			indicator: indicatorNode,
			getActiveId: () => activeIdRef.current,
			onSelect(id) {
				if (controlledActiveIdRef.current === undefined) {
					machine.setActive(id);
				} else {
					onActiveChangeRef.current?.(id);
				}
			},
			spring: springConfig,
			variant,
			orientation,
		});

		connectionRef.current = connection;
		return () => {
			connection.destroy();
			connectionRef.current = null;
		};
	}, [indicatorNode, machine, springConfig, variant, orientation]);

	useEffect(() => {
		connectionRef.current?.sync(false);
	}, [snapshot.activeId, size.width, size.height]);

	useEffect(() => {
		return () => machine.destroy();
	}, [machine]);

	const setActive = useCallback(
		(id: string) => {
			if (controlledActiveId === undefined) {
				machine.setActive(id);
			} else {
				onActiveChange?.(id);
			}
		},
		[machine, controlledActiveId, onActiveChange],
	);

	const registerIndicator = useCallback((node: SVGRectElement | SVGPathElement | null) => {
		setIndicatorNode(node);
	}, []);

	const contextValue = useMemo<MenuContextValue>(
		() => ({
			activeId: snapshot.activeId,
			setActive,
			registerIndicator,
			rootRef,
			attrs,
			filterId,
			fill,
			blur: resolvedBlur,
			size,
			variant,
		}),
		[
			snapshot.activeId,
			setActive,
			registerIndicator,
			attrs,
			filterId,
			fill,
			resolvedBlur,
			size,
			variant,
		],
	);

	return (
		<MenuContext.Provider value={contextValue}>
			<nav
				ref={rootRef}
				{...attrs.root}
				className={className}
				aria-label="Fluix menu"
			>
				<Indicator />
				<div {...attrs.list}>{children}</div>
			</nav>
		</MenuContext.Provider>
	);
}

function Item({ id, disabled = false, className, children, onClick }: MenuItemProps) {
	const context = useMenuContext();
	const active = context.activeId === id;
	const itemAttrs = context.attrs.item({ id, active, disabled });

	const handleClick: MouseEventHandler<HTMLButtonElement> = useCallback(
		(event) => {
			if (disabled) return;
			onClick?.(event);
			if (event.defaultPrevented) return;
			context.setActive(id);
		},
		[context, id, disabled, onClick],
	);

	return (
		<button
			type="button"
			{...itemAttrs}
			disabled={disabled}
			className={className}
			onClick={handleClick}
		>
			{children}
		</button>
	);
}

function Indicator({ fill, blur, className }: MenuIndicatorProps) {
	const context = useMenuContext();
	const width = Math.max(1, context.size.width);
	const height = Math.max(1, context.size.height);
	const effectiveFill = fill ?? context.fill ?? "var(--fluix-menu-indicator)";
	const effectiveBlur = blur ?? context.blur;
	const isTab = context.variant === "tab";

	return (
		<div {...context.attrs.canvas} className={className}>
			<svg
				xmlns="http://www.w3.org/2000/svg"
				width={width}
				height={height}
				viewBox={`0 0 ${width} ${height}`}
				aria-hidden="true"
			>
				{!isTab && (
					<defs>
						<filter
							id={context.filterId}
							x="-20%"
							y="-20%"
							width="140%"
							height="140%"
							colorInterpolationFilters="sRGB"
						>
							<feGaussianBlur in="SourceGraphic" stdDeviation={effectiveBlur} result="blur" />
							<feColorMatrix in="blur" type="matrix" values={GOO_MATRIX} result="goo" />
							<feComposite in="SourceGraphic" in2="goo" operator="atop" />
						</filter>
					</defs>
				)}
				{isTab ? (
					<path
						ref={context.registerIndicator}
						{...context.attrs.indicator}
						d=""
						opacity={0}
						fill={effectiveFill}
					/>
				) : (
					<g filter={`url(#${context.filterId})`}>
						<rect
							ref={context.registerIndicator}
							{...context.attrs.indicator}
							x={0}
							y={0}
							width={0}
							height={0}
							rx={0}
							ry={0}
							opacity={0}
							fill={effectiveFill}
						/>
					</g>
				)}
			</svg>
		</div>
	);
}

export const Menu = {
	Root,
	Item,
	Indicator,
};

// packages/svelte/src/Menu.svelte
<script lang="ts">
import {
	FLUIX_SPRING,
	MENU_DEFAULTS,
	connectMenu,
	createMenuMachine,
	getMenuAttrs,
	type MenuMachineState,
	type MenuOrientation,
	type MenuVariant,
	type MenuTheme,
	type SpringConfig,
} from "@fluix-ui/core";
import { setContext } from "svelte";
import type { Snippet } from "svelte";

export interface MenuProps {
	orientation?: MenuOrientation;
	variant?: MenuVariant;
	theme?: MenuTheme;
	activeId?: string | null;
	defaultActiveId?: string | null;
	onActiveChange?: (id: string) => void;
	spring?: SpringConfig;
	roundness?: number;
	blur?: number;
	fill?: string;
	className?: string;
	children: Snippet;
}

const {
	orientation = MENU_DEFAULTS.orientation,
	variant = "pill",
	theme = "dark",
	activeId: controlledActiveId,
	defaultActiveId = null,
	onActiveChange,
	spring,
	roundness = MENU_DEFAULTS.roundness,
	blur: blurProp,
	fill,
	className,
	children,
}: MenuProps = $props();

const machine = createMenuMachine({
	orientation,
	variant,
	spring,
	roundness,
	blur: blurProp,
	fill,
	initialActiveId: controlledActiveId ?? defaultActiveId,
});

let snapshot = $state.raw<MenuMachineState>(machine.store.getSnapshot());

$effect(() => {
	return machine.store.subscribe(() => {
		snapshot = machine.store.getSnapshot();
	});
});

// Reconfigure machine when props change
$effect(() => {
	machine.configure({ orientation, variant, spring, roundness, blur: blurProp, fill });
});

// Sync controlled activeId
$effect(() => {
	if (controlledActiveId !== undefined) {
		machine.setActive(controlledActiveId ?? null);
	}
});

// Notify parent of active changes
let lastActiveNotified: string | null | undefined;
$effect(() => {
	const nextActiveId = snapshot.activeId;
	if (nextActiveId && lastActiveNotified !== nextActiveId && onActiveChange) {
		onActiveChange(nextActiveId);
	}
	lastActiveNotified = nextActiveId;
});

// Refs
let rootEl: HTMLElement | null = $state(null);
let indicatorEl: SVGRectElement | SVGPathElement | null = $state(null);
let size = $state({ width: 0, height: 0 });

const attrs = $derived(getMenuAttrs({ orientation, theme, variant }));
const springConfig = $derived(spring ?? FLUIX_SPRING);
const resolvedBlur = $derived(blurProp ?? Math.min(10, Math.max(6, roundness * 0.45)));
const isTab = $derived(variant === "tab");
const svgWidth = $derived(Math.max(1, size.width));
const svgHeight = $derived(Math.max(1, size.height));
const effectiveFill = $derived(fill ?? "var(--fluix-menu-indicator)");

const filterId = `fluix-menu-goo-${Math.random().toString(36).slice(2, 8)}`;

// Keep a mutable ref for activeId (non-reactive, for connectMenu callback)
let activeIdRef = snapshot.activeId;
$effect(() => {
	activeIdRef = snapshot.activeId;
});

// ResizeObserver for root
$effect(() => {
	const root = rootEl;
	if (!root) return;

	const measure = () => {
		const rect = root.getBoundingClientRect();
		const w = Math.ceil(rect.width);
		const h = Math.ceil(rect.height);
		if (size.width !== w || size.height !== h) {
			size = { width: w, height: h };
		}
	};

	measure();
	let raf = 0;
	const observer = new ResizeObserver(() => {
		cancelAnimationFrame(raf);
		raf = requestAnimationFrame(measure);
	});
	observer.observe(root);

	return () => {
		cancelAnimationFrame(raf);
		observer.disconnect();
	};
});

// Connect menu indicator
let connection: ReturnType<typeof connectMenu> | null = null;
$effect(() => {
	const root = rootEl;
	const indicator = indicatorEl;
	if (!root || !indicator) return;

	connection = connectMenu({
		root,
		indicator,
		getActiveId: () => activeIdRef,
		onSelect(id) {
			if (controlledActiveId === undefined) {
				machine.setActive(id);
			} else {
				onActiveChange?.(id);
			}
		},
		spring: springConfig,
		variant,
		orientation,
	});

	return () => {
		connection?.destroy();
		connection = null;
	};
});

// Sync indicator when activeId or size changes
$effect(() => {
	// Read dependencies
	snapshot.activeId;
	size.width;
	size.height;
	// Trigger sync
	connection?.sync(false);
});

// Cleanup machine
$effect(() => () => machine.destroy());

// Context for MenuItem
const setActive = (id: string) => {
	if (controlledActiveId === undefined) {
		machine.setActive(id);
	} else {
		onActiveChange?.(id);
	}
};

setContext("fluix-menu", {
	get activeId() { return snapshot.activeId; },
	setActive,
	get attrs() { return attrs; },
	get variant() { return variant; },
});
</script>

<nav
	bind:this={rootEl}
	{...attrs.root}
	class={className}
	aria-label="Fluix menu"
>
	<div {...attrs.canvas}>
		<svg
			xmlns="http://www.w3.org/2000/svg"
			width={svgWidth}
			height={svgHeight}
			viewBox="0 0 {svgWidth} {svgHeight}"
			aria-hidden="true"
		>
			{#if !isTab}
				<defs>
					<filter
						id={filterId}
						x="-20%" y="-20%" width="140%" height="140%"
						color-interpolation-filters="sRGB"
					>
						<feGaussianBlur in="SourceGraphic" stdDeviation={resolvedBlur} result="blur" />
						<feColorMatrix
							in="blur" type="matrix"
							values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 20 -10"
							result="goo"
						/>
						<feComposite in="SourceGraphic" in2="goo" operator="atop" />
					</filter>
				</defs>
			{/if}
			{#if isTab}
				<path
					bind:this={indicatorEl}
					{...attrs.indicator}
					d=""
					opacity={0}
					style:fill={effectiveFill}
				/>
			{:else}
				<g filter="url(#{filterId})">
					<rect
						bind:this={indicatorEl}
						{...attrs.indicator}
						x={0}
						y={0}
						width={0}
						height={0}
						rx={0}
						ry={0}
						opacity={0}
						style:fill={effectiveFill}
					/>
				</g>
			{/if}
		</svg>
	</div>
	<div {...attrs.list}>
		{@render children()}
	</div>
</nav>
